/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainclass;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static mainclass.MainClass.hm;
import static mainclass.MainClass.list;
import static mainclass.Vertex.*;
/**
 *
 * @author aadityagadhave
 */
public class ShortestPath extends javax.swing.JFrame {

    /** Creates new form ShortestPath */
    public ShortestPath() {
        initComponents();
        
        String[] str = new String[list.size()];
        
        int i;
        
        for(i=0;i<list.size();i++)
        {
            str[i]=list.get(i).getName();
        }
        
        from.setModel(new javax.swing.DefaultComboBoxModel<>(str));
        
        for(i=0;i<list.size();i++)
        {
            str[i]=list.get(i).getName();
        }
        
        to.setModel(new javax.swing.DefaultComboBoxModel<>(str));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        from = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        to = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shortest Path");

        jLabel2.setFont(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("From vertex");

        from.setFont(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("To Vertex");

        to.setFont(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jButton1.setFont(new java.awt.Font("Apple Braille", 0, 14)); // NOI18N
        jButton1.setText("Compute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(from, 0, 260, Short.MAX_VALUE)
                            .addComponent(to, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    static void dijkstra(int n, int dist[], int parent[], int set[])
    {
        int i,j;
        //JOptionPane.showMessageDialog(null, n);
        for(i=0;i<n-1;i++)
        {
            int u=minDistance(dist,set,n);
            set[u]=1;
            
            if(!revInd.containsKey(u) || !hm.containsKey(revInd.get(u)))
                continue;
            
            int size=hm.get(revInd.get(u)).size();
            ArrayList<Graph>al=hm.get(revInd.get(u));
            
            for(j=0;j<size;j++)
            {
                Graph g=al.get(j);
                int v=ind.get(g.getName());
                
                if(set[v]==0 && dist[u]+g.getWeight()<dist[v])
                {
                    dist[v]=dist[u]+g.getWeight();
                    //JOptionPane.showMessageDialog(null, dist[v]+" "+revInd.get(v)+" "+g.getWeight()+" "+revInd.get(u));
                    parent[v]=u;
                }
            }
        }
    }
    
    static int minDistance(int dist[], int set[],int n)
    {
        int min=Integer.MAX_VALUE;
        int min_index=-1; 
      
        for (int v = 0; v < n; v++)
        { 
            if (set[v]==0 && dist[v]<=min) 
            {
                min=dist[v];
                min_index=v; 
            }
        }
      
        return min_index; 
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int i;
        
        String start=(String)from.getSelectedItem();
        String end=(String)to.getSelectedItem();

        int[] dist;
        dist=new int[list.size()+1];
        int[] set;
        set=new int[list.size()+1];
        int[] parent;
        parent=new int[list.size()+1];
        int j;
        for(j=0;j<=list.size();j++)
        {
            dist[j]=Integer.MAX_VALUE;
            set[j]=0;
            parent[j]=-1;
        }

        int key=ind.get(start);
        dist[key]=0;
        parent[key]=-1;
        //displayInd();
        dijkstra(list.size()+1,dist,parent,set);
        //JOptionPane.showMessageDialog(null, "Successfully Processed");
        
        int flg=0;
        int key1=ind.get(end);

        while(parent[key1]!=-1)
            key1=parent[key1];

        if(key1==key)
            flg=1;
        String str="";
        if(flg==1)
        {

            ArrayList<String>path=new ArrayList<String>();
            key1=ind.get(end);

            while(parent[key1]!=-1)
            {
                String var=revInd.get(key1);
                path.add(var);
                key1=parent[key1];
            }

            path.add(start);
      
            for(j=path.size()-1;j>=1;j--)
            {
                str=str+path.get(j);
                str=str+"->";
            }
            str+=path.get(j);
            key1=ind.get(end);
            str=str+"\nCost is: "+dist[key1];
        }
        else
        {
            str+="No Path Exists";
        }

                //JOptionPane.showMessageDialog(null, i);
                
          textArea.setText(str);
            
         //JOptionPane.showMessageDialog(null, "Successfully Processed");
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortestPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortestPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortestPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortestPath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortestPath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> from;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JComboBox<String> to;
    // End of variables declaration//GEN-END:variables

}
